# Generated by Django 2.2.24 on 2021-08-25 22:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodian',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Veli', 'verbose_name_plural': 'Veliler'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Eğitmen', 'verbose_name_plural': 'Eğitmenler'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['name'], 'verbose_name': 'Atölye', 'verbose_name_plural': 'Atölyeler'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='student',
        ),
        migrations.AddField(
            model_name='instructor',
            name='i_students',
            field=models.ManyToManyField(to='app.Student', verbose_name='Eğitmenin Öğrencileri'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='l_student',
            field=models.ManyToManyField(to='app.Student', verbose_name='Dersin Öğrencisi'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_lessons',
            field=models.ManyToManyField(to='app.Lessons', verbose_name='Öğrencinin Dersleri'),
        ),
        migrations.RemoveField(
            model_name='custodian',
            name='c_students',
        ),
        migrations.AddField(
            model_name='custodian',
            name='c_students',
            field=models.ManyToManyField(to='app.Student', verbose_name='Velinin Öğrencisi'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Veli adı'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Veli soyadı'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='tc',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Veli tc'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Eğitmen Adı'),
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='i_lessons',
        ),
        migrations.AddField(
            model_name='instructor',
            name='i_lessons',
            field=models.ManyToManyField(blank=True, null=True, to='app.Lessons', verbose_name='Eğitmenin Dersleri'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Eğitmen Soyadı'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='tc',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Eğitmen TC'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='l_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Instructor', verbose_name='Dersin Eğitmeni'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Öğrencinin Adresi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, max_length=8, verbose_name='Öğrencinin Doğum Rarihi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Öğrencinin e-Posta'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Öğrenci Adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Öğrenci Soyadı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Öğrencinin GSM'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_custodian',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.Custodian', verbose_name='Öğrencinin Velisi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=30, verbose_name='Öğrencinin Okulu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tc',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Öğrenci TC'),
        ),
    ]
