# Generated by Django 2.2.24 on 2021-08-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210826_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_custodian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_lessons',
        ),
    ]
