# Generated by Django 2.2.24 on 2021-08-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210826_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodian',
            name='c_students',
        ),
    ]
