# Generated by Django 2.2.24 on 2021-08-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_custodian_c_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='c_students',
            field=models.ManyToManyField(to='app.Student', verbose_name='Velinin Öğrencisi'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_custodian',
            field=models.OneToOneField(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Custodian', verbose_name='Öğrencinin Velisi'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_lessons',
            field=models.ManyToManyField(blank=True, null=True, to='app.Lessons', verbose_name='Öğrencinin Dersleri'),
        ),
    ]
