# Generated by Django 2.2.24 on 2021-08-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210826_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='i_students',
            field=models.ManyToManyField(blank=True, null=True, to='app.Student', verbose_name='Eğitmenin Öğrencileri'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='l_student',
            field=models.ManyToManyField(blank=True, null=True, to='app.Student', verbose_name='Dersin Öğrencisi'),
        ),
    ]
