# Generated by Django 2.2.24 on 2021-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210826_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_custodian',
        ),
        migrations.AddField(
            model_name='student',
            name='s_custodian',
            field=models.ManyToManyField(blank=True, max_length=30, null=True, to='app.Custodian', verbose_name='Öğrencinin Velisi'),
        ),
    ]
